name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies in functions
        working-directory: functions
        run: npm install

      - name: Run tests with coverage in functions
        working-directory: functions
        run: npm test -- --coverage

      # - name: Set up Java 17
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: temurin
      #     java-version: 17

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
