name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        shell: bash
        working-directory: functions
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Prepare Google Application Credentials
        shell: bash
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > "google-application-credentials.json"

      - name: Debug - Show First 10 Lines of Service Account JSON
        run: head -n 10 google-application-credentials.json

      - name: Use Firebase Personal Budget Control Project
        shell: bash
        env:
          GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
        run: firebase use personal-budget-control-8dc91 --debug

      - name: Authenticate with Service Account
        run: gcloud auth activate-service-account --key-file=google-application-credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json

      - name: Deploy Firebase functions
        shell: bash
        run: firebase deploy --only functions --non-interactive --debug --project personal-budget-control-8dc91

      - name: Remove credentials file
        if: success() || failure()
        run: |
          rm google-application-credentials.json
