name: Test Artifact Upload/Download

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test file
        run: echo "Hello World" > test.txt

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download test artifact
        uses: actions/download-artifact@v4
        with:
          name: test-artifact
          path: downloaded
      - name: List downloaded files
        run: ls downloaded
